name: Recently played games

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-steam-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.steam.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "0"
          plugin_steam_sections: recently-played
          plugin_steam_achievements_limit: 0
